# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-16 16:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180116_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 1, 16, 16, 25, 22, 794128, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 16, 16, 25, 22, 794128, tzinfo=utc)),
        ),
    ]
